trigger:
  - main

stages:
  - stage: CI
    displayName: "Continuous Integration"

    jobs:
      - job: InstallLintAndBuildNodeApp
        displayName: "Install dependancies, Lint and Build Node Application"

        pool:
          vmImage: ubuntu-latest

        steps:
          - task: UseNode@1
            inputs:
              version: 22.x
            displayName: "Use Node.js Ecosystem"

          - task: Npm@1
            inputs:
              command: install
            displayName: "Install Dependancies"

          - task: Npm@1
            inputs:
              customCommand: run lint
            displayName: "Run Linter"

          - task: Npm@1
            inputs:
              customCommand: run build
            displayName: "Build Application"

      - job: DockerBuildAndPush
        displayName: "Build and Push Docker Image"

        pool:
          vmImage: ubuntu-latest

        steps:
          - task: Docker@2
            inputs:
              command: buildAndPush
              Dockerfile: ./Dockerfile
              repository: amandwandwe/retail-platform-ui
              containerRegistry: Docker Hub (amandwandwe)
              tags: |
                latest
            displayName: "Build and Push the Image to Docker Hub"

  - stage: CD
    displayName: "Continuous Deployment"

    dependsOn: CI

    jobs:
      - deployment: DeployToK8S
        displayName: "Deploy to Kubernetes"

        environment:
          name: dev
          resourceType: VirtualMachine
          tags: dev

        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: "Checkout sources"

                - bash: |
                    cd ./terraform/
                    terraform init
                  displayName: "Initialize Terraform"

                - bash: |
                    cd ./terraform/
                    terraform plan
                  displayName: "Plan Terraform"
